FROM php:7.4-apache

# Forzar actualización de fuentes APT
RUN apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false || { sleep 10; apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false; }

# Instalar dependencias
RUN apt-get install -y wget unzip libzip-dev

# Instalar extensiones PHP
RUN docker-php-ext-install pdo pdo_mysql zip

# Limpiar caché
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

# Ajustar permisos y manejar enlaces simbólicos
RUN chown -R www-data:www-data /var/www/html/web /var/www/html/vendor \
    && chmod -R 755 /var/www/html/web /var/www/html/vendor \
    && ln -sf /var/www/html/vendor/twbs/bootstrap/dist/fonts/ /var/www/html/web/fonts

RUN a2enmod rewrite \
    && echo '<VirtualHost *:80>\n    ServerName localhost\n    DocumentRoot /var/www/html/web\n    <Directory /var/www/html/web>\n        Options Indexes FollowSymLinks\n        AllowOverride All\n        Require all granted\n    </Directory>\n</VirtualHost>' > /etc/apache2/sites-available/000-default.conf \
    && a2enmod rewrite

EXPOSE 80

ENV DB_HOST=mariadb \
    DB_NAME=sample \
    DB_USER=sampleuser \
    DB_PASS=samplepass