FROM php:7.2-apache

# Usar un mirror alternativo de APT para mayor confiabilidad
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

# Actualizar e instalar dependencias por separado
RUN apt-get update
RUN apt-get install -y wget unzip libzip-dev

# Instalar extensiones PHP
RUN docker-php-ext-install pdo pdo_mysql zip

# Limpiar caché
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN a2enmod rewrite \
    && echo '<Directory /var/www/html/web>\n    AllowOverride All\n    Require all granted\n</Directory>' > /etc/apache2/conf-available/docker.conf \
    && a2enconf docker \
    && sed -i 's!/var/www/html!web!g' /etc/apache2/sites-available/000-default.conf

EXPOSE 80

ENV DB_HOST=mariadb \
    DB_NAME=sample \
    DB_USER=sampleuser \
    DB_PASS=samplepass