name: Publish to Docker Hub
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - '.github/workflows/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push WEB
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.web
          push: true
          tags: jcabo65/php-sample-web:latest
      - name: Build & Push DB
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.db
          push: true
          tags: jcabo65/php-sample-db:latest
